[package]
name = "alibaba"
version = "0.1.0"
edition = "2021"
description = "nothing"
license = "Apache-2.0"
keywords = ["alibaba"]
repository = "https://github.com/1654364091/alibaba.git"

[dependencies]
